name: "Prepare test environment"
description: "Prepares test environment"

runs:
  using: "composite"
  steps:
    - name: Setup Go
      uses: actions/setup-go@v2
      with:
        go-version: '${{ env.GO_VERSION }}'

    - name: Setup python
      uses: actions/setup-python@v4
      with:
        python-version: '${{ env.PYTHON_VERSION }}'