name: "Run static code check"
description: "Performs static code checks."

runs:
  using: "composite"
  steps:
      - name: Setup virtual environment
        run: |
          python3 -m venv venv
        shell: bash

      - name: Install tests requirements
        run: |
          source ./venv/bin/activate
          pip3 install -r test/requirements.txt
        shell: bash

      - name: Log versions
        run: |
          go version
        shell: bash

      - name: Go Linter
        uses: golangci/golangci-lint-action@v3
        with:
          args: --config=golangci-lint.yml --out-${NO_FUTURE}format colored-line-number
          skip-cache: true

      - name: Python Linter
        run: |
          source ./venv/bin/activate
          python3 -m flake8 test
        shell: bash